### ISSUE TITLE
taro +taro_ui 最新版本搭配 tarojs-router-next 在VSCODE中类型提示有问题

### ISSUE THREAD

**Issue by leesama** [lblblong/tarojs-router-next#10]
{
  "name": "testA",
  "version": "1.0.0",
  "private": true,
  "description": "dd",
  "templateInfo": {
    "name": "taro-ui",
    "typescript": true,
    "css": "less"
  },
  "scripts": {
    "build:weapp": "taro build --type weapp",
    "build:swan": "taro build --type swan",
    "build:alipay": "taro build --type alipay",
    "build:tt": "taro build --type tt",
    "build:h5": "taro build --type h5",
    "build:rn": "taro build --type rn",
    "build:qq": "taro build --type qq",
    "build:jd": "taro build --type jd",
    "build:quickapp": "taro build --type quickapp",
    "dev:weapp": "npm run build:weapp -- --watch",
    "dev:swan": "npm run build:swan -- --watch",
    "dev:alipay": "npm run build:alipay -- --watch",
    "dev:tt": "npm run build:tt -- --watch",
    "dev:h5": "npm run build:h5 -- --watch",
    "dev:rn": "npm run build:rn -- --watch",
    "dev:qq": "npm run build:qq -- --watch",
    "dev:jd": "npm run build:jd -- --watch",
    "dev:quickapp": "npm run build:quickapp -- --watch"
  },
  "browserslist": [
    "last 3 versions",
    "Android >= 4.1",
    "ios >= 8"
  ],
  "author": "",
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@tarojs/cli": "3.2.1",
    "@tarojs/components": "3.2.1",
    "@tarojs/runtime": "3.2.1",
    "@tarojs/taro": "3.2.1",
    "lodash": "4.17.15",
    "@tarojs/react": "3.2.1",
    "react": "^17.0.0",
    "react-dom": "^17.0.0",
    "taro-ui": "^3.0.0-alpha.3"
  },
  "devDependencies": {
    "@babel/core": "^7.8.0",
    "@tarojs/mini-runner": "3.2.1",
    "@tarojs/webpack-runner": "3.2.1",
    "@types/react": "^17.0.2",
    "@types/webpack-env": "^1.13.6",
    "@typescript-eslint/eslint-plugin": "^4.15.1",
    "@typescript-eslint/parser": "^4.15.1",
    "babel-preset-taro": "3.2.1",
    "eslint": "^6.8.0",
    "eslint-config-taro": "3.2.1",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-react": "^7.8.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "stylelint": "9.3.0",
    "tarojs-router-next": "^1.3.2",
    "typescript": "^4.1.0"
  }
}

**Comment by leesama** [comment]
![image](https://user-images.githubusercontent.com/16167426/114126266-af150a80-992a-11eb-9399-91ea561d206f.png)

**Comment by leesama** [comment]
现在发现是@vue_runtime-dom@3.0.11@@vue\runtime-dom\dist\runtime-dom.d.ts导致的

**Comment by lblblong** [comment]
是的，@vue 包中的一些定义会和 jsx 发生冲突，导致编辑器无法正常识别 @tarojs/components，但是编译不会报错

**Comment by lblblong** [comment]
@leesama 已经删除 vue 的依赖项，发布了 1.3.3 的版本，应该可以了
