### ISSUE TITLE
Taro 的navigateTo 的emit 

### ISSUE THREAD

**Issue by zimo888** [lblblong/tarojs-router-next#12]
https://nervjs.github.io/taro/docs/apis/route/navigateTo

有时候需要子页面选择一些内容后，弹出，然后给父页面传值，这个功能还是需要用的。

```
Taro.navigateTo({
  url: 'test?id=1',
  events: {
    // 为指定事件添加一个监听器，获取被打开页面传送到当前页面的数据
    acceptDataFromOpenedPage: function(data) {
      console.log(data)
    },
    someEvent: function(data) {
      console.log(data)
    }
    ...
  },
  success: function (res) {
    // 通过eventChannel向被打开页面传送数据
    res.eventChannel.emit('acceptDataFromOpenerPage', { data: 'test' })
  }
})

```

**Comment by lblblong** [comment]
你的场景是 page1 跳转到 page2 选择一些内容，然后返回给到 page1 吗

**Comment by zimo888** [comment]
对，是这个场景

**Comment by lblblong** [comment]
有更好的解决方案，不是用事件

用 tarojs-router-next 实现：
```typescript
// pages/page1/index
const res = await Router.navigate({ url: "/pages/page2/index" });
console.log(res)

// pages/page2/index

const { backData } = useRouter();
backData({data: 'test'})
```

**Comment by lblblong** [comment]
参考这两个页面：
https://github.com/lblblong/tarojs-router-next/blob/master/examples/react/src/pages/index/index.tsx
https://github.com/lblblong/tarojs-router-next/blob/master/examples/react/src/pages/sel-city/index.tsx

**Comment by zimo888** [comment]
明白了，从全局变量里取，谢谢

**Comment by lblblong** [comment]
不需要你放到全局变量里
我封装这个库最初就是为了更方便的跨页面取值，而不需要使用者放到全局变量里，或者通过 event 传递

**Comment by zimo888** [comment]
再次感谢，还一个小问题
https://github.com/lblblong/tarojs-router-next/blob/master/src/router.ts 这里的31行，是不是有两个参数
```
    await fn({ route, params: options.params })
```

![image](https://user-images.githubusercontent.com/4545006/114664592-81ff9800-9d2e-11eb-9ef4-86d3bc58bbdc.png)

**Comment by lblblong** [comment]
这里用的是 koa-compose 这个库，第二个参数是可选的，可能与你本地的版本不匹配
![image](https://user-images.githubusercontent.com/18625523/114664969-07834800-9d2f-11eb-8d71-c84def845d78.png)

**Comment by zimo888** [comment]
OK,Thank you 这个问题关了吧
