### ISSUE TITLE
底部tabBar配置的跳转，不走中间件对吗，使用 Router.toUser方法可以是这样吗

### ISSUE THREAD

**Issue by ccbyland** [lblblong/tarojs-router-next#17]
底部tabBar配置的跳转，不走中间件对吗，使用 Router.toUser方法可以是这样吗

**Comment by lblblong** [comment]
Router.to** 调用的方法都会走中间件的，但是记得跳转到 tabbar 页面时要设置跳转类型

```typescript
Router.toUser({ type: NavigateType.switchTab })
```

**Comment by lblblong** [comment]
我明白你意思了，刚刚没仔细看

小程序自带的 TabBar 跳转是不会走中间件的，只有调用 Router.to** 或者 Router.navigate 才会走中间件

这种目前建议自定义 tabbar
