### ISSUE TITLE
使用分包编译不通过

### ISSUE THREAD

**Issue by 576** [lblblong/tarojs-router-next#19]
Router.home = {
  177 |         to: to,
> 178 |         : .DSStore,
      |         ^
  179 |         function: function (options) { return Router.navigate({ url: "/subpackages/pages/.DS_Store/index" }, options); },
  180 |         toHome: function (options) { return Router.navigate({ url: "/subpackages/pages/home/index" }, options);

**Comment by lblblong** [comment]
可以给个最小的复现仓库吗

**Comment by 576** [comment]
你用taro创建个demo工程加入分包试试 这是我的配置 subpackages: [
    {
      name: 'home',
      root: 'subpackages',
      pagesPath: 'subpackages/pages',
      pages: ['pages/home/index'],
    },
  ],

**Comment by lblblong** [comment]
https://github.com/lblblong/tarojs-router-next/blob/master/examples/react/src/app.config.ts

示例里是有分包的代码的，我本地运行没有问题
看起来像是你的 `src/subpackages/pages` 下有一个 .DS_Store 的文件夹，这个文件夹也是页面吗

**Comment by 576** [comment]
没有这个文件夹  我看了你的配置感觉我的配置也没有问题

**Comment by lblblong** [comment]
可能是你的 IDE 自动隐藏了这个文件夹，建议进资源管理器里看看是否存在这个文件夹

**Comment by lblblong** [comment]
你是 Mac 系统吗

**Comment by 576** [comment]
是的     没有看到这个文件

**Comment by lblblong** [comment]
那你把 `node_module/tarojs-router-next/dist/router/index.ts` 的 177 到 181 行截图给我看下，应该是 mac 系统上的隐藏文件/文件夹导致的，如果是这个问题我需要做一下过滤

**Comment by 576** [comment]
我感觉需要过滤一下

**Comment by 576** [comment]
/** 获取上一个页面携带过来的参数 */
    Router.getParams = function () {
        var _a;
        var instance = taro_1.getCurrentInstance();
        var params = Object.assign({}, (_a = instance.router) === null || _a === void 0 ? void 0 : _a.params);
        delete params.route_key;
        return params;
    };
    Router.toIndex = function (options) { return Router.navigate({ url: "/pages/index/index" }, options); };
    Router.toLogin = function (options) { return Router.navigate({ url: "/pages/login/index" }, options); };
    return Router;
}());
exports.Router = Router;

**Comment by 576** [comment]
改好回复一下

**Comment by lblblong** [comment]
刚刚发布了 2.2.4 版本，你升级 `tarojs-router-next` 和 `tarojs-router-next-plugin` 的版本再试试看

**Comment by 576** [comment]
Router.home = {
  175 |         to: to,
> 176 |         : .DSStore,
      |         ^
  177 |         function: function (options) { return Router.navigate({ url: "/subpackages/pages/.DS_Store/index" }, options); }
  178 |     };
  179 |     return Router;

**Comment by 576** [comment]
不行

**Comment by 576** [comment]
find . -name '*.DS_Store' -type f -delete  执行这个可以了

**Comment by lblblong** [comment]
那应该就是目录下存在隐藏文件的问题，我刚刚发布了 2.2.5 ，你再更新版本试试
