### ISSUE TITLE
同步的路由方法功能不生效

### ISSUE THREAD

**Issue by Xiaolong145682** [lblblong/tarojs-router-next#21]
`
// pages/authCenter/index
Router.back({ a: 'xxxxxx' })

// pages/home/index
const handleToAuthCenter = async (): Promise<void> => {
    try {
      const data = await Router.toAuthCenter()
      console.log('data ==>: ', data)
    } catch (error) {
      console.warn('error: ', error)
    }
  }`
跳转至 authCenter 页面，返回时没有带回来数据

**Comment by lblblong** [comment]
可以给个最小可复现的仓库吗

**Comment by Xiaolong145682** [comment]
@lblblong 项目地址如下，项目启动后访问 `/#/home`
https://github.com/Xiaolong145682/cheetha

**Comment by lblblong** [comment]
> @lblblong 项目地址如下，项目启动后访问 `/#/home`
> `
> // 安装依赖
> yarn
> 
> // 生成 router 文件
> yarn tarocodegen
> 
> // 运行项目
> yarn dev:h5
> `
> https://github.com/Xiaolong145682/cheetha

好的，我看看

**Comment by lblblong** [comment]
我测试是可以拿到返回的数据的

![image](https://user-images.githubusercontent.com/18625523/122526791-42ff0300-d04d-11eb-8c8d-b191f8e44bb1.png)

但我做了一些修改，可能是不支持 `@yocdev/tarocodegen` 生成的 `app.config.ts` ，换成手写的路由配置就行了

![image](https://user-images.githubusercontent.com/18625523/122526874-59a55a00-d04d-11eb-8459-0a4df515be4c.png)

**Comment by Xiaolong145682** [comment]
> 我测试是可以拿到返回的数据的
> 
> ![image](https://user-images.githubusercontent.com/18625523/122526791-42ff0300-d04d-11eb-8c8d-b191f8e44bb1.png)
> 
> 但我做了一些修改，可能是不支持 `@yocdev/tarocodegen` 生成的 `app.config.ts` ，换成手写的路由配置就行了
> 
> ![image](https://user-images.githubusercontent.com/18625523/122526874-59a55a00-d04d-11eb-8459-0a4df515be4c.png)



> 我测试是可以拿到返回的数据的
> 
> I test to get the data back
> 
> ![image](https://user-images.githubusercontent.com/18625523/122526791-42ff0300-d04d-11eb-8c8d-b191f8e44bb1.png)
> 
> 但我做了一些修改，可能是不支持 `@yocdev/tarocodegen` 生成的 `app.config.ts` ，换成手写的路由配置就行了
> 
> But I’ve made some changes, perhaps not to support the@yocdev codegen generated app. So, uh... Ts, switch to a hand-written routing configuration
> 
> ![image](https://user-images.githubusercontent.com/18625523/122526874-59a55a00-d04d-11eb-8459-0a4df515be4c.png)

好的，我再确认一下

**Comment by Xiaolong145682** [comment]
还是不行，你还修改了哪两个文件，我看你改动了三个文件。

**Comment by lblblong** [comment]
就只改动了 `app.config.ts` ，另外两个文件是运行 `yarn tarocodegen` 后自动改的

![image](https://user-images.githubusercontent.com/18625523/122559046-63d94f80-d071-11eb-8928-123eed3c9fd1.png)

![image](https://user-images.githubusercontent.com/18625523/122559071-6b005d80-d071-11eb-9b11-805712e2595b.png)

![image](https://user-images.githubusercontent.com/18625523/122559086-70f63e80-d071-11eb-9ac2-ea467a4f7ed6.png)

**Comment by lblblong** [comment]
> 还是不行，你还修改了哪两个文件，我看你改动了三个文件。

你是什么系统，可能 taro 在 h5 端存在系统的差异

**Comment by lblblong** [comment]
知道问题了，是因为自定义了 h5 的路由路径导致的

![image](https://user-images.githubusercontent.com/18625523/122631207-a72cd000-d0fc-11eb-8204-69c6eec4b44e.png)

解决方法是不使用自定义路径，注释掉这个配置项

![image](https://user-images.githubusercontent.com/18625523/122631236-e2c79a00-d0fc-11eb-9785-54ea9826d504.png)

很奇怪的是，我在 windows 上没有注释掉这一行也可以正常运行，也就是说自定义路径在 windows 上没有生效....，在 linux 下才测试出这个问题

**Comment by Xiaolong145682** [comment]
是自定义路由导致的，后续会对这里做优化吗，另外 router_key 的作用是什么，可以隐藏掉吗

**Comment by lblblong** [comment]
> 是自定义路由导致的，后续会对这里做优化吗，另外 router_key 的作用是什么，可以隐藏掉吗

目前不打算对自定义路由做处理，会比较麻烦，要多读一些配置文件

router_key 是用来标识页面唯一的，因为业务中会出现进入同一个页面多次

好像是可以通过一些方法不显示在 url 上的，这个我看看能不能处理

**Comment by lblblong** [comment]
@Xiaolong145682 刚刚发布了版本 2.3.0 ，已经在 url 中隐藏了 route_key，并且添加了自定义路由路径支持，你更新试试

**Comment by lblblong** [comment]
https://gitpod.io#snapshot/f36dcb63-9d58-4637-b7c6-326553c79716
测试了一下，没问题了

**Comment by Xiaolong145682** [comment]
好的，非常感谢！
