### ISSUE TITLE
最新版本H5页面跳转不会将上一层页面设置为 display: none; 导致页面堆叠

### ISSUE THREAD

**Issue by leesama** [lblblong/tarojs-router-next#23]
使用taro.navigateTo 正常

**Comment by lblblong** [comment]
好像是taro自身问题，多刷新几下试试，或者删掉 dist 目录重新构建

**Comment by leesama** [comment]
这也不能让用户多刷新几次呀。。但是确实用taro的跳转就正常了

**Comment by lblblong** [comment]
了解，可以提供一个可复现的demo吗，我看看问题

**Comment by lblblong** [comment]
@leesama 试一下刚刚发布的 2.3.1 版本，应该解决第一个页面不隐藏问题了

**Comment by leesama** [comment]
https://codesandbox.io/s/long-bird-28mju?file=/src/pages/a/index.tsx

**Comment by leesama** [comment]
正常了
