### ISSUE TITLE
页面通过链接访问的时候不执行中间件，如何解决？

### ISSUE THREAD

**Issue by chmubai** [lblblong/tarojs-router-next#24]
页面通过链接访问的时候不执行中间件，如何解决？

**Comment by lblblong** [comment]
目前没办法实现外部直接进入目标页面之前执行中间件

这种情况只能修改业务为只给一个外部入口（页面），包括分享也是从同一个入口进，要跳转的具体页面通过参数带入，然后通过 Router.navigate 跳转，这样是会执行中间件的

**Comment by lblblong** [comment]
也就是非通过 Router.to 或者 Router.navigate 的跳转方式都不会执行中间件
除了进入小程序的第一个页面，其他跳转都能通过 Router 的方法
