### ISSUE TITLE
 Router.navigate()无法实现replace功能

### ISSUE THREAD

**Issue by chmubai** [lblblong/tarojs-router-next#27]
![image](https://user-images.githubusercontent.com/16893170/125259292-c270b100-e331-11eb-8072-c6aadc3c6958.png)
replace没有生效

**Comment by lblblong** [comment]
参数传错了哦

```typescript
Router.navigate({ url: '/pages/index/index' }, { type: NavigateType.redirectTo })
```

**Comment by chmubai** [comment]
> 参数传错了哦
> 
> ```ts
> Router.navigate({ url: '/pages/index/index' }, { type: NavigateType.redirectTo })
> ```
确实是，http://lblblib.gitee.io/tarojs-router-next/guide/quike/navigate文档里面需要改一下

**Comment by lblblong** [comment]
感谢反馈，已经纠正文档了
