### ISSUE TITLE
中间件无法拿到data参数

### ISSUE THREAD

**Issue by itmanyong** [lblblong/tarojs-router-next#28]
场景：跳转其他需要权限的页面，中间件拦截了需要去登录页面，但我我未能在中间件或登录页去找到data参数！,是否能将data参数做下处理如同ext一样呢?
![image](https://user-images.githubusercontent.com/53500371/128625335-c49c2729-2896-4966-bcba-14a762fa150e.png)

**Comment by lblblong** [comment]
好的，下个版本会支持中间件访问 data 的功能

**Comment by lblblong** [comment]
@itmanyong 已经添加了，更新到 2.4.0 版本就可以了
