### ISSUE TITLE
路由跳转返回失效 报错 MiniProgramError {errMsg:navigateBack: fail navigateBack intercepted }

### ISSUE THREAD

**Issue by slixina** [lblblong/tarojs-router-next#29]
![24321629713413_ pic](https://user-images.githubusercontent.com/49421399/130431522-2809ea99-1b7a-431c-9c8d-0a5c4526128c.jpg)

有的机型会出现跳转返回卡住，返回不了页面（iPhone XR）
查看日志发现是报错【MiniProgramError {errMsg:navigateBack: fail navigateBack intercepted }】
请问应该怎样解决

版本：
"@tarojs/taro": "3.2.6",
"tarojs-router-next": "^2.2.2",

**Comment by lblblong** [comment]
是用  Router.back 方法返回的吗，可以提供下代码吗

**Comment by slixina** [comment]
是的，使用Router.back 返回
![image](https://user-images.githubusercontent.com/49421399/130542775-d1e00b38-c2b0-4185-81df-bdd5fc037b43.png)
这是跳转到目标页的方法

![image](https://user-images.githubusercontent.com/49421399/130542840-ad419962-82fe-4653-86b2-02541ceab1fe.png)
这是目标页操作完成后的返回方法

**Comment by slixina** [comment]
最新发现：和机型无关，和页面跳转路径有关

不会有问题的测试路径 tab页（mine）进入订单列表页<使用toOrderList，没有加type>， 订单列表页进入申请退款页<to....  没加type  >    申请退款页完成操作 Router.back没问题

有问题的测试路径 index页进入下单路径（都采用toPage方式 默认没带type） 到支付完成页 点击回到mine页（使用toMine，type为switchTab）再走上面的流程 返回就会报错

**Comment by lblblong** [comment]
你这段代码有可能会多次触发 Router.back，你改动成下面这样试试

```typescript
let timer

clearTimeout(timer)
timer = setTimeout(()=>{
  Router.back(...)
}, 2000)
```

**Comment by slixina** [comment]
> 你这一段代码有可能会多次触发 Router.back，你修改成这样的功能
> 
> ```ts
> 让 计时器
> 
> clearTimeout （定时器）
> 的定时器 =  setTimeout的（（）=> {
>   路由器。背部（ ... ）
> } ， 2000 ）
> ```

试了一下 没有效果

**Comment by lblblong** [comment]
emm，我这边 back 方法很简单，相当于是直接调用 Taro.navigateBack() 了
https://github.com/lblblong/tarojs-router-next/blob/c2242fe119cc934d46171d9c5e43c0232cdb947c/packages/tarojs-router-next/src/router/index.ts#L83

应该还是你代码逻辑的问题，你看看能不能提供一个能复现问题的仓库，我就比较好知道问题在哪了

**Comment by slixina** [comment]
> emm，我后面的方法很简单，相当于直接调用Taro.navigateBack()了
> https://github.com/lblblong/tarojs-router-next/blob/c2242fe119cc934d46171d9c5e43c0232cdb947c/packages/tarojs-router-next/src/router/index.ts#L83
> 
> 应该还是你代码逻辑的问题，你看看能不能提供一个能复现的问题仓库不能，我就比较好知道问题在哪了

刚刚试着抽出一个仓库，抽出的仓库没有复现这个问题，请问您有解决这个问题的思路吗？报错信息在前面的截图里

**Comment by lblblong** [comment]
你在 Router.back 这句之前打印一下当前路由路径，看看是否已经退回了 tabbar 的页面

```typescript
console.log('before back：',Taro.Current.page?.path)
Router.back(...)
```

**Comment by lblblong** [comment]
如果已经退到  tabbar 页面，再调用 back 方法是有可能出现这个异常的，因为页面栈已经没有可以退的了

**Comment by lblblong** [comment]
你还可以在 tabbar 的页面直接加个按钮然后调用 back 方法，看看会不会报这个异常，如果也抛出这个异常，那就差不多找到问题了

**Comment by slixina** [comment]
排查了一下 好像和小程序的原生组件page-container有关

**Comment by lblblong** [comment]
那我知道问题了，page-container 是没有页面路径的，如果要关闭 page-container 的话，要使用原生的返回方法：Taro.navigateBack()，不要使用 Router.back

**Comment by slixina** [comment]
解决了 确实是page-container导致的这个问题

**Comment by slixina** [comment]
解决了 确实是page-container导致的这个问题
