### ISSUE TITLE
安装了tarojs-router-next-plugin后编译失败

### ISSUE THREAD

**Issue by 553875193** [lblblong/tarojs-router-next#30]
![image](https://user-images.githubusercontent.com/38682458/131276636-bdc91de4-47f2-46cc-8472-015ab30e2559.png)

**Comment by lblblong** [comment]
taro 什么版本的

**Comment by 553875193** [comment]
> 芋头什么版本的
不好意思 是我的plugins放错位置了

**Comment by 553875193** [comment]
![image](https://user-images.githubusercontent.com/38682458/131277694-de905598-f25c-405a-baa8-5e77a85595f1.png)
现在有了另外一个问题
"@tarojs/taro": "2.2.11",
"tarojs-router-next": "^2.4.0",
 "tarojs-router-next-plugin": "^2.4.0"

**Comment by lblblong** [comment]
不支持在taro2.x使用，只支持 3.x，建议升级一下  taro 版本

**Comment by 553875193** [comment]
> 不支持在taro2.x使用，只支持3.x，建议升级一下taro版本
哦 好的，谢谢
