### ISSUE TITLE
多层的页面路由无法监听

### ISSUE THREAD

**Issue by jsLyLeeHi** [lblblong/tarojs-router-next#31]
![image](https://user-images.githubusercontent.com/31194716/132213075-a3fc15b7-e6a7-4b83-a2c7-39deb9f7a1ec.png)

**Comment by lblblong** [comment]
是的，目前只支持一级目录下的页面，不支持二级目录：
http://lblblib.gitee.io/tarojs-router-next/guide/quike/qa#pages-%E4%B8%8B%E7%9A%84%E4%BA%8C%E7%BA%A7%E7%9B%AE%E5%BD%95%E6%B2%A1%E6%9C%89%E7%94%9F%E6%88%90%E8%B7%AF%E7%94%B1%E6%96%B9%E6%B3%95
