### ISSUE TITLE
分包设置疑问

### ISSUE THREAD

**Issue by QingYuanO** [lblblong/tarojs-router-next#32]
![屏幕截图 2021-09-09 201043](https://user-images.githubusercontent.com/42159029/132683352-26354f5d-acf0-4357-a2e5-efc306f5ab5f.png)
这样的分包方法，我没有设置name和pagesPath但是好像也生成了方法。
（其实这个样分包，跳转的链接就和放在pages里是一样的。）

**Comment by lblblong** [comment]
对的，开发模式下会默认为 src/pages 所有一级页面目录生成路由方法，和分不分包其实没关系

但如果是非 src/pages 下一级目录的页面进行分包的话，是一定要指定 name 和 pagesPath 的，不然不会生成路由方法

你这样写在开发模式下应该是没有问题的，但打包之后可能就有问题了，因为打包会过滤掉没在 app.config 的 pages（最外层pages，非 subPackages 里面的 pages） 里面声明的页面

**Comment by lblblong** [comment]
因为打包会过滤掉没在 app.config 的 pages 中声明的页面，所以建议你还是要为每一个分包指定 name 和 pagesPath，避免打包后路由方法不存在。

```

**Comment by QingYuanO** [comment]
![image](https://user-images.githubusercontent.com/42159029/132786712-94ddaf43-b8d6-4d9b-aa4b-2b501e7e5648.png)
这样分包和这样的目录结构，好像配不了。
