### ISSUE TITLE
路由中间件无法感知页面返回

### ISSUE THREAD

**Issue by idootop** [lblblong/tarojs-router-next#35]
![图片](https://user-images.githubusercontent.com/35302658/136887798-ff4fa491-374f-444a-bc93-1f48e4192fa9.png)

如图，我们希望通过一个路由中间件监听路由事件，包括何时打开页面，何时关闭/返回页面。

但比较尴尬的是，当前中间件在await next()之后并不是等待页面被关闭，而是指打开了页面，所以丧失了在中间件中监听路由关闭的能力。

![图片](https://user-images.githubusercontent.com/35302658/136888139-6511062f-e36c-4074-b7c5-ef9c7be354d9.png)

所以，比较符合直觉的是：await next() => 等待当前页面被关闭/返回

**Comment by idootop** [comment]
对应的，用户通过设备上的返回键返回上一级页面时，能否监听到对应路由事件？

**Comment by lblblong** [comment]
可以监听到路由返回的，但不是在中间件中
比如从 A 页面进入 B 页面，然后在 A 页面监听 B 页面返回后执行一些代码：
```typescript
await Router.toB()
// B 页面返回后执行的代码
```

**Comment by lblblong** [comment]
> 对应的，用户通过设备上的返回键返回上一级页面时，能否监听到对应路由事件？

按键返回同样通过上面的方法也能监听到

**Comment by lblblong** [comment]
如果你们需要一个统一的路由返回监听，可以通过 Proxy 对 Router 的 toXX 方法进行一层代理来完成

**Comment by idootop** [comment]
感谢回复❤️

我们现在的解决方案是在所有页面包裹一层自定义的Page组件，

在Page组件的初始化和销毁事件里回调页面的打开和关闭

```typescript
export function useRouteListener(): void {
  const id = useMemo(() => uuid(), []);
  useInit(() => {
    addPage(id);
  });
  useDispose(() => {
    removePage(id);
  });
}
```

但是这也只是感知页面的打开和关闭事件，没法以中间件的形式全局handle路由传递的数据（打开/关闭）

当然把router做一层代理是一个方法，但是不够优雅，这件事本身适合在中间件去处理，

再在外面封一层代理岂不是脱裤子放屁--多此一举？

我们现在讨论的是能否在tarojs-router-next的中间件里添加感知页面返回及其数据（ const returnedData = await next() ）的能力，

而不是在不改变tarojs-router-next已有功能的基础上找一些workaround去达到这个目的。

所以这是一个新功能的一个提议。

以上。再次感谢。

**Comment by lblblong** [comment]
新增了 `registerRouterBackListener` 全局注册路由返回监听函数，看能不能满足你们的业务场景：
http://lblblib.gitee.io/tarojs-router-next/api/method/register-router-back-listener/

要更新到 2.6.0

**Comment by idootop** [comment]
> 了解，你说的这个功能我在做中间件这一块的时候有思考过
> 
> 之所以没有设计成你说的这样，是因为小程序的返回操作没办法中断或者等待
> 
> 这就导致我们在跳转到新页面时，`所有中间件 await next() 之前的代码执行完毕了才会跳转到新页面`，但是在返回的时候`没办法做到所有中间件的 await next() 之后的代码执行完毕才返回到上一个页面`
> 
> 我也希望流程是下面这样的：
> 
> ```ts
> // 1. 在 A 页面跳转到 B 页面，这里的 result 是中间件进出页面之后返回的
> const result = await Router.toB()
> 
> // 2. 中间件 await next() 之前的代码执行
> // 3. 成功进入 B 页面
> // 4. 触发返回
> // 5. 中间件 await next() 之后的代码执行
> // 6. 成功返回到 A 页面
> // 7. 第一步的 result 拿到 B 页面的返回值
> ```
> 
> 但实际的流程会是这样：
> 
> ```ts
> // 1. 在 A 页面跳转到 B 页面，这里的 result 是页面返回时立即获得的
> const result = await Router.toB()
> 
> // 2. 中间件 await next() 之前的代码执行
> // 3. 成功进入 B 页面
> // 4. 触发返回
> // 5. 第一步的 result 拿到 B 页面的返回值
> // 6. 成功返回到 A 页面
> // 7. 中间件 await next() 之后的代码执行
> ```

原来如此，因为我之前是做Flutter开发的没搞过小程序，所以对小程序的路由限制不是很熟悉。

不过我好奇一点：

现在的 router.toXXX 方法是一个Promise 异步方法，可以通过await去得到页面的返回值。

调用 router.toXXX 返回了一个 Promise，通过PageData.setPagePromise把这个promise的res，rej注册到PageData.pagePromise里

现在的处理是在这个promise里进行了中间件的执行，并把emitPageBack后的数据传递了出来

那有没有可能把它拆分成两个promise，一个用来把页面返回数据传递给中间件，

一个等待中间件执行完毕后的结果并把最终结果反给router.toXXX调用者？

这样我们就有了在中间件里感知并修改返回数据的能力（虽然不能阻止页面的返回，不过貌似也能把back方法做一层代理，在调用前先执行返回中间件，在中间件里判断是否允许其返回上一页，或者重定向路由页面等）

我一会去试下可不可行

**Comment by idootop** [comment]
> > 了解，你说的这个功能我在做中间件这一块的时候有思考过
> > 之所以没有设计成你说的这样，是因为小程序的返回操作没办法中断或者等待
> > 这就导致我们在跳转到新页面时，`所有中间件 await next() 之前的代码执行完毕了才会跳转到新页面`，但是在返回的时候`没办法做到所有中间件的 await next() 之后的代码执行完毕才返回到上一个页面`
> > 我也希望流程是下面这样的：
> > ```ts
> > // 1. 在 A 页面跳转到 B 页面，这里的 result 是中间件进出页面之后返回的
> > const result = await Router.toB()
> > 
> > // 2. 中间件 await next() 之前的代码执行
> > // 3. 成功进入 B 页面
> > // 4. 触发返回
> > // 5. 中间件 await next() 之后的代码执行
> > // 6. 成功返回到 A 页面
> > // 7. 第一步的 result 拿到 B 页面的返回值
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但实际的流程会是这样：
> > ```ts
> > // 1. 在 A 页面跳转到 B 页面，这里的 result 是页面返回时立即获得的
> > const result = await Router.toB()
> > 
> > // 2. 中间件 await next() 之前的代码执行
> > // 3. 成功进入 B 页面
> > // 4. 触发返回
> > // 5. 第一步的 result 拿到 B 页面的返回值
> > // 6. 成功返回到 A 页面
> > // 7. 中间件 await next() 之后的代码执行
> > ```
> 
> 原来如此，因为我之前是做Flutter开发的没搞过小程序，所以对小程序的路由限制不是很熟悉。
> 
> 不过我好奇一点：
> 
> 现在的 router.toXXX 方法是一个Promise 异步方法，可以通过await去得到页面的返回值。
> 
> 调用 router.toXXX 返回了一个 Promise，通过PageData.setPagePromise把这个promise的res，rej注册到PageData.pagePromise里
> 
> 现在的处理是在这个promise里进行了中间件的执行，并把emitPageBack后的数据传递了出来
> 
> 那有没有可能把它拆分成两个promise，一个用来把页面返回数据传递给中间件，
> 
> 一个等待中间件执行完毕后的结果并把最终结果反给router.toXXX调用者？
> 
> 这样我们就有了在中间件里感知并修改返回数据的能力（虽然不能阻止页面的返回，不过貌似也能把back方法做一层代理，在调用前先执行返回中间件，在中间件里判断是否允许其返回上一页，或者重定向路由页面等）
> 
> （补下图）
> 
> <img alt="图片" width="729" src="https://user-images.githubusercontent.com/35302658/137586999-a29537aa-479a-4147-96d5-54b352696dae.png">
> 
> 我一会去试下可不可行

搞定了，测试见下图：

<img width="663" alt="图片" src="https://user-images.githubusercontent.com/35302658/137605567-3c3136d2-c8b7-4c21-831a-d16970b0fc2f.png">

<img width="1672" alt="图片" src="https://user-images.githubusercontent.com/35302658/137605558-6832be45-c1f2-4a60-b41c-fabdcb518d0e.png">

第一个是调用onBack方法回传指定数据

第二个是按系统返回键回传空数据

二者都能在中间件中监听到

至此，我们拥有了在中间件中全局监听并修改页面返回值的能力。

@lblblong 这个功能可以提交PR不，还是暂时保持当前的中间件执行流程设计？

一会我再研究下把onBack方法作层代理，由onBack中间件决定是否触发onBack，不过好像没发阻止通过设备返回键返回上一页，一个折中的办法是，不允许返回时再强行push回去页面，但这样就污染了页面的生命周期了（创建/销毁），代价比较昂贵，用户体验应该也不会太好的。

以上。

**Comment by idootop** [comment]
补图

<img width="1405" alt="图片" src="https://user-images.githubusercontent.com/35302658/137606110-0788621e-49db-4ed4-8721-9d1f50eb0524.png">

只是监听修改返回数据的能力，阻止页面返回上一页的能力目测暂时没啥好的解决方案（主要没办法拦截系统级的返回）～
