### ISSUE TITLE
路由中间件只能拦截使用Router类跳转的场景

### ISSUE THREAD

**Issue by LuoQaxa** [lblblong/tarojs-router-next#38]
你好想请教一下：
目前路由中间件只能拦截使用Router类跳转的场景。
当直接访问需要受拦截的页面，拦截并不生效，这其实是没有真正的拦截页面，有什么方式可以做到真正的拦截路由吗？
我想到的可能的方案：
1. taro-router是否有暴露方法能处理渲染前的逻辑
2. 目前我们的项目里实现了一个权限高阶组件，在每个页面根组件引入权限高阶组件包裹页面组件，但是这样的问题是很容易漏掉，在思考有没有办法在编译时自动引入该组件包裹

**Comment by lblblong** [comment]
没有办法真正的拦截路由跳转
你说的的拦截其实是进入到目标页面后先展示一个占位页面，然后鉴权不符再跳转而已，这也不是拦截

我认为最好的方案就是只对外提供一个入口页面，然后所有的跳转由代码控制，这样就除了对外暴露的那个页面的其他页面都不存在直接访问的情况了

**Comment by LuoQaxa** [comment]
1. 我们项目里写了权限组件AuthChecker包裹了app.tsx 中的props.chidlren, 在这个组件里做了登录态校验和参数完整性校验，拦截组件的渲染，我认为就是正常的拦截，就是类似vue-router里的拦截页面渲染。

受你这个插件的启发在编译时通过ast操作给页面组件添加对应的WithAuthCheckerHoc包裹。

2. 你说的只对外提供一个入口页面，那你怎么判断下一步该跳转到哪个路由呢？

**Comment by lblblong** [comment]
你们这种拦截方式不会产生多次跳转动画吗，因为在调用 Taro.navigateTo 的一瞬间，页面进入的动画就开始了，然后动画执行过程中你们代码检测到用户登录态异常进行了一次重定向，就会产生第二个页面入栈动画

只提供一个入口页面的方案需要事先定义好分享规则
比如分享一个文章详情页出去：pages/launch/index?type=news&id=123
分享一个用户：pages/launch/index?type=user&id=222

然后在 launch 页通过一个字典和分享入参 type 来判断进入哪个页面（或者执行哪段逻辑）

**Comment by LuoQaxa** [comment]
没有二次路由跳转，没有重定向的过程，具体可以看下面代码
// app.tsx <Authorized>包裹props.children
```ts
mport { Provider } from 'react-redux';
import Authorized from 'src/components/Authorized';
import { store } from './store/index';

class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <Authorized>{this.props.children}</Authorized>
      </Provider>
    );
  }
}

export default App;

```
// 权限组件 Authorized
```ts
import { useDidShow } from '@tarojs/taro';
import React, { useState } from 'react';
import { useDispatch } from 'react-redux';
import { fetchUserInfo } from 'src/store/user';
import { getQuery } from 'src/utils/url';

const defaultRouteStatus = {
  isRender: false,
  isError: false,
  errMsg: '',
};

type AuthorizedProps = Record<string, any>;
export const IsRenderContext = React.createContext(defaultRouteStatus);
const Authorized: React.FC<AuthorizedProps> = (props) => {
  const dispatch = useDispatch();

  const [routerStatus, setRouteStatus] = useState(defaultRouteStatus);
  /**
   * 1. 参数校验
   */
  const queryCheck = (cb) => {
    
    cb && cb();
  };

  /**
   * 2. 处理ticket同步登录态，获取用户id
   */
  const handleLogin = async () => {
    const { ticket } = getQuery();
    if (ticket) {
      try {
        await dispatch(fetchUserInfo(ticket));
      } catch (error) {
        setRouteStatus({
          ...routerStatus,
          isError: true,
          errMsg: error.msg || '同步登录态失败',
        });
        return;
      }
    }
    setRouteStatus({
      isRender: true,
      isError: false,
      errMsg: '',
    });
  };

  useDidShow(() => {
    queryCheck(handleLogin);
  });

  return <IsRenderContext.Provider value={routerStatus}>{props.children}</IsRenderContext.Provider>;
};

export default Authorized;
```

// 用于页面渲染拦截hoc：WithBeforeRouter
```ts
import { useContext } from 'react';
import { AtActivityIndicator } from 'taro-ui';
import { IsRenderContext } from '../Authorized';
import styles from './index.module.scss';

const WithAuthCheck = (component) => {
  const Component = component;
  return () => {
    // eslint-disable-next-line react-hooks/rules-of-hooks
    const { isError, isRender, errMsg } = useContext(IsRenderContext);

    if (isError) {
      return (
        <div className={styles.err_wrap}>
          <img src={require('src/assets/images/error.png')} alt="" />
          <div className={styles.text}>{errMsg}</div>
        </div>
      );
    }
    if (!isRender) {
      return (
        <div className={styles.loading_wrap}>
          <AtActivityIndicator />
        </div>
      );
    }
    return <Component />;
  };
};

export default WithAuthCheck;

```


// 在具体页面组件使用对应
```ts
class Home {}
export default WithBeforeRouter(Home);

```

**Comment by LuoQaxa** [comment]
你说的通过参数来判断进入页面，这需要在项目初期就采取这样的方案，有提前的规划才行，不过也是一种解决方案

**Comment by lblblong** [comment]
你们编译的目标平台是 H5 吗

**Comment by LuoQaxa** [comment]
是的

**Comment by lblblong** [comment]
那就对了，这个库主要是给小程序用的，在小程序里会产生多次页面跳转动画，对用户来说体验很差，我说的只提供一个入口也是小程序下的方案，h5的话用户想进哪个页面改一下url就过去了

h5 我有另一个 react 路由库（暂时没有开源），也有中间件功能，但你们这个项目已经用 taro 写了，要改起来估计很麻烦，明天我写个 demo，说不定你们下个项目可以考虑下

**Comment by LuoQaxa** [comment]
好的，等你空了看下你的react路由库demo

**Comment by lblblong** [comment]
路由部分是 `lbl-react-router` 这个库，虽然还没开源，但是我已经用在一些生产环境的项目里了

https://stackblitz.com/edit/react-ts-vujzsc?file=router/routes.tsx

**Comment by edwards19900128** [comment]
> 没有二次路由跳转，没有重定向的过程，具体可以看下面代码 // app.tsx 包裹props.children
> 
> ```ts
> mport { Provider } from 'react-redux';
> import Authorized from 'src/components/Authorized';
> import { store } from './store/index';
> 
> class App extends Component {
>   render() {
>     return (
>       <Provider store={store}>
>         <Authorized>{this.props.children}</Authorized>
>       </Provider>
>     );
>   }
> }
> 
> export default App;
> ```
> 
> // 权限组件 Authorized
> 
> ```ts
> import { useDidShow } from '@tarojs/taro';
> import React, { useState } from 'react';
> import { useDispatch } from 'react-redux';
> import { fetchUserInfo } from 'src/store/user';
> import { getQuery } from 'src/utils/url';
> 
> const defaultRouteStatus = {
>   isRender: false,
>   isError: false,
>   errMsg: '',
> };
> 
> type AuthorizedProps = Record<string, any>;
> export const IsRenderContext = React.createContext(defaultRouteStatus);
> const Authorized: React.FC<AuthorizedProps> = (props) => {
>   const dispatch = useDispatch();
> 
>   const [routerStatus, setRouteStatus] = useState(defaultRouteStatus);
>   /**
>    * 1. 参数校验
>    */
>   const queryCheck = (cb) => {
>     
>     cb && cb();
>   };
> 
>   /**
>    * 2. 处理ticket同步登录态，获取用户id
>    */
>   const handleLogin = async () => {
>     const { ticket } = getQuery();
>     if (ticket) {
>       try {
>         await dispatch(fetchUserInfo(ticket));
>       } catch (error) {
>         setRouteStatus({
>           ...routerStatus,
>           isError: true,
>           errMsg: error.msg || '同步登录态失败',
>         });
>         return;
>       }
>     }
>     setRouteStatus({
>       isRender: true,
>       isError: false,
>       errMsg: '',
>     });
>   };
> 
>   useDidShow(() => {
>     queryCheck(handleLogin);
>   });
> 
>   return <IsRenderContext.Provider value={routerStatus}>{props.children}</IsRenderContext.Provider>;
> };
> 
> export default Authorized;
> ```
> 
> // 用于页面渲染拦截hoc：WithBeforeRouter
> 
> ```ts
> import { useContext } from 'react';
> import { AtActivityIndicator } from 'taro-ui';
> import { IsRenderContext } from '../Authorized';
> import styles from './index.module.scss';
> 
> const WithAuthCheck = (component) => {
>   const Component = component;
>   return () => {
>     // eslint-disable-next-line react-hooks/rules-of-hooks
>     const { isError, isRender, errMsg } = useContext(IsRenderContext);
> 
>     if (isError) {
>       return (
>         <div className={styles.err_wrap}>
>           <img src={require('src/assets/images/error.png')} alt="" />
>           <div className={styles.text}>{errMsg}</div>
>         </div>
>       );
>     }
>     if (!isRender) {
>       return (
>         <div className={styles.loading_wrap}>
>           <AtActivityIndicator />
>         </div>
>       );
>     }
>     return <Component />;
>   };
> };
> 
> export default WithAuthCheck;
> ```
> 
> // 在具体页面组件使用对应
> 
> ```ts
> class Home {}
> export default WithBeforeRouter(Home);
> ```

请教一下，这个方案小程序可以用吗
