### ISSUE TITLE
路由携带参数丢失问题

### ISSUE THREAD

**Issue by jsLyLeeHi** [lblblong/tarojs-router-next#39]
复现步骤：
假设有A,B,C三个页面
现在需要从A页面跳转到B页面，但是需要在跳转之前使用'tarojs-router-next'的registerMiddleware做登录验证
如果没登录，则先跳转到C页面完成登录，登录成功后继续从A页面跳转到B页面，这时A页面跳转到B页面携带的参数消失
实例：
![image](https://user-images.githubusercontent.com/31194716/142379051-e782cae2-2d1c-4a63-aa76-b20276fd1a7b.png)
从岗位列表跳转到岗位详情，需要校验登录，拉起弹出框
![image](https://user-images.githubusercontent.com/31194716/142379136-da4e1a62-03e6-4084-8851-944d0aeb2cb6.png)
点击手机号注册登录，完成操作后，跳转到详情页面的jobId消失

**Comment by jsLyLeeHi** [comment]
![image](https://user-images.githubusercontent.com/31194716/142379335-28058ccf-42d2-4d34-a401-a6d6dcdbf7a9.png)
![image](https://user-images.githubusercontent.com/31194716/142379402-24e43019-ea28-4ab1-81fb-7d64afdfb8c7.png)

**Comment by lblblong** [comment]
登录成功后，是先返回到列表页，然后再点击进入详情页吗

**Comment by jsLyLeeHi** [comment]
登录成功后自动跳转到详情页

**Comment by jsLyLeeHi** [comment]
![image](https://user-images.githubusercontent.com/31194716/142380194-1499d935-1c34-494f-8576-9535bad3aafe.png)

**Comment by jsLyLeeHi** [comment]
![image](https://user-images.githubusercontent.com/31194716/142380372-80942711-4725-4b1d-998d-18cfa914d1bf.png)

**Comment by jsLyLeeHi** [comment]
差不多是这个意思

**Comment by lblblong** [comment]
jobId 是用 params 传的还是 data

**Comment by lblblong** [comment]
即使替换成 params 是可行的也不建议在中间件中进行其他路由操作之后再调用 next 方法，最好更换一下实现方式
