### ISSUE TITLE
关于route_key

### ISSUE THREAD

**Issue by Laev** [lblblong/tarojs-router-next#4]
router_key在一些原本就有参数的跳转场景中，会再在地址后面加"?router_key=xxxx"
如 ”localhost:8080/home?id=1000“ 跳转时有可能发生 ”localhost:8080/home?id=1000?router_key=xxxx“ 
而不是”localhost:8080/home?id=1000&router_key=xxxx“ 
而且有可能无限添加”router_key“

请问router_key是否可以提供配置将其隐藏，或者再更新该值的时候检测地址是否携带其他参数或router_key

**Comment by lblblong** [comment]
router_key 是用来避免重复进入同一个页面的时候，覆盖页面之间参数用的，没有办法隐藏，只能跟在url后面
你说的这种情况：”localhost:8080/home?id=1000?router_key=xxxx“，我猜应该是参数放错了位置：
```typescript
// 这样放参数就会导致你说的那种情况
Router.navigate({ url: '/pages/home/index?id=1000' })

// 这样就不会有问题
Router.navigate({ url: '/pages/home/index' }, { params: { id: 1000 } })
```

但确实我应该考虑到 url 中已经带参的情况，下一个版本会解决这个问题

**Comment by lblblong** [comment]
url 中带参的问题已经处理了，发布了 1.3.0 的版本，但是包名修改了，因为 npm 账号登录不上了
新的包名：tarojs-router-next
