### ISSUE TITLE
路由中间件似乎对程序启动后加载的第一个页面不生效

### ISSUE THREAD

**Issue by velley** [lblblong/tarojs-router-next#44]
大佬你好，我现在的需求就是：小程序进入首页之前就要进行拦截，并判断用户是否登录且有访问权限。因为首页的几个请求已经涉及到要传token了。但是路由中间件对此无效。看了还是通过http请求后的状态码来进行判断并跳转了。

**Comment by lblblong** [comment]
在首页之前添加一个启动页，只保留启动页这一个入口，从启动页再跳转到其他页面
