### ISSUE TITLE
在Taro v3.0.27及以上版本上报错

### ISSUE THREAD

**Issue by liumeA** [lblblong/tarojs-router-next#5]
在Taro v3.0.26正常，但在升级 3.0.27 及3.1.1后报错

TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_0___default.a.navigateTo is not a function

**Comment by liumeA** [comment]
我将此项目中源代码clone到本地，只将此项目依赖修改为3.1.1并重新编译，而后在我的项目中运行正常，没有发现错误

**Comment by lblblong** [comment]
我测试了没问题哦，你是怎么导入使用的，代码发上来看看

**Comment by liumeA** [comment]
我目前项目是Taro v3.1.1
以下是我关于tarojs-router的使用,借鉴示例代码封装的方法

import { Router } from 'tarojs-router';
import { routes } from './route';

// 登陆
export function toLogin() {
	return Router.navigate(routes.login);
}

// 文章列表
export function toArticleList(type: number) {
	return Router.navigate(routes.article_list, { params: { type } });
}


我将此项目fork到我的账户下，同时只修改此项目package.json中的tarojs依赖为3.1.1，运行就正常

**Comment by lblblong** [comment]
emmm...
我试了 3.0.27 没啥问题..
有检查 tarojs-cli 版本和项目 taro 相关库版本一致吗

我更新了taro 依赖到 3.1.1 了，应该没问题了
包名修改了：https://www.npmjs.com/package/tarojs-router-next

**Comment by liumeA** [comment]
tarojs-cli 我是放在项目的package.json中，通过npx的方式使用的，和项目taro版本一致；
我测试使用tarojs-router-next，没有问题了
