### ISSUE TITLE
路由参数丢失问题

### ISSUE THREAD

**Issue by effortcheep** [lblblong/tarojs-router-next#51]
小程序处于激活状态，在某个页面不做任何操作，手机息屏或者锁屏解锁后，再通过 Router.getParams() 获取不到 之前的参数

**Comment by lblblong** [comment]
原因是微信小程序在息屏时也会触发 onHide 生命周期方法，而 Taro 会在 onHide 生命周期重置全局的 Current 实例里的 router，所以导致在息屏期间通过 Router.getParams() 就获取不到参数

建议是在进入页面时保存 getParams 的参数，之后就不要再通过 getParams 获取参数了

Taro 的 useRouter 就是做的类似的处理
```ts
export const useRouter = (dynamic = false) => {
  const React = reactMeta.R
  return dynamic ? Current.router : React.useMemo(() => Current.router, [])
}
```
