### ISSUE TITLE
`route.config.ts`不支持导入类型？

### ISSUE THREAD

**Issue by benny-eu** [lblblong/tarojs-router-next#52]
`route.config.ts`导入其他类型，编译后会变成any？

**Comment by lblblong** [comment]
是的，这个实现起来暂时没想到好的方案，一般路由参数都比较简单，就都写在 route.config.ts 里吧

**Comment by lblblong** [comment]
突然想到一个方案，等有空我试试，最近比较忙

**Comment by benny-eu** [comment]
你好，刚试了一下。类型名称是正确了，但是编译后的`index.d.ts`中没有实际导入该类型。
