### ISSUE TITLE
Can't resolve 'src/lib/compose'

### ISSUE THREAD

**Issue by jianhao2010303** [lblblong/tarojs-router-next#56]
版本： 3.1.0
问题描述： Can't resolve 'src/lib/compose'
错误：

ERROR in ./node_modules/tarojs-router-next/dist/middleware/index.js 180:16-42
Module not found: Error: Can't resolve 'src/lib/compose' in 'E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\tarojs-router-next\dist\middleware'
resolve 'src/lib/compose' in 'E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\tarojs-router-next\dist\middleware'
  Parsed request is a module
  using description file: E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\tarojs-router-next\package.json (relative path: ./dist/middleware)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\tarojs-router-next\dist\middleware\node_modules doesn't exist or is not a directory
      E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\tarojs-router-next\dist\node_modules doesn't exist or is not a directory
      E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\tarojs-router-next\node_modules doesn't exist or is not a directory
      E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\node_modules doesn't exist or is not a directory
      looking for modules in E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules
        E:\workspace_xuct\xuct-calendar\xut-calendar-vant-weapp\node_modules\src doesn't exist
      E:\workspace_xuct\xuct-calendar\node_modules doesn't exist or is not a directory
      E:\workspace_xuct\node_modules doesn't exist or is not a directory
      E:\node_modules doesn't exist or is not a directory
 @ ./node_modules/tarojs-router-next/dist/index.js 20:19-42
 @ ./src/pages/aboutus/index.tsx 20:0-40 100:10-30
 @ ./src/app.config.ts 343:15-46

**Comment by lblblong** [comment]
已修复，安装 3.1.1

**Comment by jianhao2010303** [comment]
没推npm？

**Comment by lblblong** [comment]
推了，可能没刷新，或者你用了国内镜像源？

**Comment by jianhao2010303** [comment]
拉下来了。有5分钟延迟。

**Comment by lblblong** [comment]
ok
