### ISSUE TITLE
异常无法捕获

### ISSUE THREAD

**Issue by daofeng-coder** [lblblong/tarojs-router-next#57]
用NavigateType.navigateTo去跳转tabBar，会出现异常，但无法捕获

**Comment by lblblong** [comment]
什么异常呢，有报错信息吗

**Comment by daofeng-coder** [comment]
tabBar页面用navigateTo去跳转会报错对吧，这个错误.catch无法捕捉到

**Comment by lblblong** [comment]
可以 catch 跳转的异常了，v3.2.0

**Comment by daofeng-coder** [comment]
哇，感谢感谢，这么快就更新了，我赶快体验一下
