### ISSUE TITLE
定义附加数据问题

### ISSUE THREAD

**Issue by LrainchenL** [lblblong/tarojs-router-next#59]
`router`
![image](https://user-images.githubusercontent.com/24932661/199405349-cf5aad42-f20a-48aa-be2f-389924f81abf.png)
![image](https://user-images.githubusercontent.com/24932661/199405551-0850f89c-9bc9-473a-90a7-36fd1fb5fccb.png)
![image](https://user-images.githubusercontent.com/24932661/199405457-7c326348-8fea-4917-bde3-b052e7522d3d.png)
![image](https://user-images.githubusercontent.com/24932661/199405574-74bfd7f3-1b96-40df-a068-207d11a5b77c.png)
![image](https://user-images.githubusercontent.com/24932661/199405591-13032665-a1cc-461d-8eb0-1e9945a3f119.png)
`app.js`
![image](https://user-images.githubusercontent.com/24932661/199405657-c66a6d1a-3326-424c-8ec1-ef904eb03b52.png)
`pages`
![image](https://user-images.githubusercontent.com/24932661/199405729-23bee5a2-8737-48ed-ab9f-c429ef251dff.png)
![image](https://user-images.githubusercontent.com/24932661/199405758-2600b4ae-f2e7-43e9-8dc6-757cb0b8ed72.png)
在这样的页面配置下，使用`Router.to*`方法中间件的校验部分就不执行，而使用`Router.navigate({ url: '/pages/archives/index', ext: { mustLogin: true } })`就可以，不知道是不是有哪里配置错误，一直没有找到问题
`Router.toArchives()`只返回这个
![image](https://user-images.githubusercontent.com/24932661/199406573-0a42d217-e1ca-4e93-96a8-46c2c25f3df1.png)
`Router.navigate`方法就可以正常执行
![image](https://user-images.githubusercontent.com/24932661/199406873-8036672e-d971-4d3c-ad07-ad3c5dd8243e.png)

**Comment by lblblong** [comment]
页面下的路由配置文件不支持 .js，只支持 .ts，把 route.config.js 改成 route.config.ts 就行了
