### ISSUE TITLE
请问这个能加动画吗

### ISSUE THREAD

**Issue by crixusshen** [lblblong/tarojs-router-next#6]
如题

**Comment by crixusshen** [comment]
路由切换时的动画

**Comment by lblblong** [comment]
不可以的，路由切换是小程序自带的功能，除非微信提供了自定义过渡动画的方法
如果要实现页面切换的动画，可以在单个 Page 中模拟页面的跳转，始终是 dom 之间的切换，而不是 page 之间的切换
