### ISSUE TITLE
路由调转传递data没有类型提示

### ISSUE THREAD

**Issue by Typeve** [lblblong/tarojs-router-next#67]
`export type Data = {
  title: string
  author?: string
  content?: string
  views?: string
}
`
详情页面配置如上类型，但是跳转方法没有类型提示，只提示未提供options的自变量
![微信图片_20230721180801](https://github.com/lblblong/tarojs-router-next/assets/45506880/8ebcafba-a757-4e06-b79b-5d9ae33d20c2)
我跳到生成的to方法中,看到import找不到类型文件模块
![微信图片_20230721181420](https://github.com/lblblong/tarojs-router-next/assets/45506880/e87a3080-c3ce-4385-8d64-81ac18bd94a2)

运行环境是windows11

**Comment by clayzx** [comment]
![image](https://github.com/lblblong/tarojs-router-next/assets/9709390/d886da12-c4e4-4359-ba23-0624e9d54c97)
我这也没有类型提示，看生成的文件里有import(‘Path’).Data，但是就是没类型提示。
是不是这种import方法的问题，能不能定义route.config.ts里面定义的时候使用页面名称+Params/Data的方式，然后在生成的文件头中把对应的route.config.ts中的[PageName+Params/Data]类型import进去，这样应该不会出现类型不提示的问题吧。

另外，在Watching状态下为页面新增route.config.ts，并不会为toXXX方法生成类型，只会生成一个static toRoute: any; 
而且，每为一个其他页面添加一个route.config.ts，就会多生成一句static toRoute: any; ，这样导致重复定义。
不过，推出watching，重新执行yarn dev:weapp就生成正确了。 
![image](https://github.com/lblblong/tarojs-router-next/assets/9709390/85bb8c3f-a75a-4d40-928a-ebd2f09c47f3)

有类型检查可以避免很多Bug，挺重要的，希望老板有空修复一下！

**Comment by lblblong** [comment]
已经处理了，可以更新到 3.3.0

---- 
@clayzx 生成 toRoute 的没有复现，可以提供一个可以复现仓库吗

**Comment by lblblong** [comment]
@clayzx toRoute的问题也修复了，更新到 v3.3.1

**Comment by clayzx** [comment]
牛，这效率相当的高嘛，还没反应得过来就修复好了，
这插件非常的好用，非常感谢！

By Clay.

发件人: ***@***.***>
发送时间: 2023年9月13日 16:23
收件人: ***@***.***>
抄送: Clay ***@***.***>; ***@***.***>
主题: Re: [lblblong/tarojs-router-next] 路由调转传递data没有类型提示 (Issue #67)


@clayzx<https://github.com/clayzx> toRoute的问题也修复了，更新到 v3.3.1

―

**Comment by clayzx** [comment]
兄弟，打扰一下：

toXXX()的返回类型，参照Params和Data一样，使用在toute.config.ts中定义的BackData类型；

建议可以把toXXX()的返回类型定义在toute.config.ts中，如：BackData；
在生成的toXXX()方法上，使用toXXX<T = BackData>()，这样既可以使用默认定义在toute.config.ts中的BackData，又可以在特定场景下自己传入特定类型，不过不建议使用toXXX<特性类型>()这种，一般一个页面就定义一个返回类型。

添加这个功能应该比较简单，如果可以的话，劳烦老板有空添加一下，谢谢！

By Clay.
