### ISSUE TITLE
你有没有taro h5路由切换实现转场动画的思路？

### ISSUE THREAD

**Issue by crixusshen** [lblblong/tarojs-router-next#7]
taro封装的太死了，在h5上的路由切换是没有任何转场动画的，就是屏幕闪了下，但是想实现转场动画，发现根本加不上，你有思路吗？

**Comment by lblblong** [comment]
没用 taro 写过 h5...
小程序中新的页面入栈旧的页面不会被销毁，taro生成的h5做的可能比较粗暴，新的页面(dom)入栈，应该是直接把旧的销毁了，来不及做一个旧页面淡出或其他效果

要在h5端实现页面转场动画，应该可以通过编写一个 Taro 插件在打包的时候做一些处理：https://taro-docs.jd.com/taro/docs/plugin
