### ISSUE TITLE
taro react使用的时候分包情况会生成一个冗余的路由

### ISSUE THREAD

**Issue by king-jam1** [lblblong/tarojs-router-next#72]
![image](https://github.com/lblblong/tarojs-router-next/assets/57787889/6ea8212e-2fec-4603-80e9-3b20ea1a20bd)

**Comment by king-jam1** [comment]
希望可以删除这个冗余路由的生成

**Comment by lblblong** [comment]
在 build 之后不会有这个路由
----
建议不要把分包放在主包的 pages 目录下
