### ISSUE TITLE
当使用reLaunch类型的跳转时，会错误的触发 registerRouterBackListener 后退拦截器回调

### ISSUE THREAD

**Issue by Ryan-CW-Code** [lblblong/tarojs-router-next#76]
如题，当使用reLaunch类型的跳转时。 如果有缓存页面就会触发 registerRouterBackListener 后退拦截器回调。 但是不应该触发的

**Comment by lblblong** [comment]
目前没有什么好的办法解决这个问题，现在的实现是在页面的 onUnloud 回调中触发，但其实是不知道当前页面是否是因为页面回退才销毁的

**Comment by Ryan-CW-Code** [comment]
这样的话确实，只能不那么依靠 registerRouterBackListener 拦截器了
