### ISSUE TITLE
路由已经生成，控制台提示生成，源码也生成，但是提示不存在函数

### ISSUE THREAD

**Issue by Lron-boy** [lblblong/tarojs-router-next#78]
只有一部分生成的可以跳转，有的却报错，函数不存在
![image](https://github.com/lblblong/tarojs-router-next/assets/61782856/35fdd87c-7112-4e96-8fe1-408402b01dec)
![image](https://github.com/lblblong/tarojs-router-next/assets/61782856/6967b84f-5af5-465b-ab09-d758af4bc594)
![image](https://github.com/lblblong/tarojs-router-next/assets/61782856/d587897c-40d2-4ccc-aa7e-6e3c05788ae8)
![image](https://github.com/lblblong/tarojs-router-next/assets/61782856/ea48ab4e-ab84-4123-9baa-25699c358006)
![image](https://github.com/lblblong/tarojs-router-next/assets/61782856/824b5b93-ca84-4664-8dae-ceeea1fbf372)

**Comment by lblblong** [comment]
![image](https://github.com/lblblong/tarojs-router-next/assets/18625523/2890adb0-6499-4811-b0fd-5f15839dd6cb)

**Comment by lyricdon** [comment]
开启了好像也没用啊,  突然不行了,   文件没变化
