### ISSUE TITLE
路由方法没有实际生成

### ISSUE THREAD

**Issue by lyricdon** [lblblong/tarojs-router-next#79]
taro3.6.6  之前可以的, 突然就不行了,  控制台有日志输出, 文件没有变动

![image](https://github.com/lblblong/tarojs-router-next/assets/12814752/33d828f8-f94c-4ea6-b0dd-4b5cea03cf61)
![image](https://github.com/lblblong/tarojs-router-next/assets/12814752/79fda667-0167-4c22-a885-486b5e97f41a)

**Comment by lyricdon** [comment]
之前的路由虽然报错但是还能继续跳转,  新加的不行了

**Comment by lblblong** [comment]
现在是taro什么版本

**Comment by lyricdon** [comment]
3.4.4已解决
