### ISSUE TITLE
能在taro-vue3中使用吗？

### ISSUE THREAD

**Issue by qianyihao123** [lblblong/tarojs-router-next#9]
我在taro-vue3项目中使用, 提示我了一些关于react的报错 1.You might have mismatching versions of React and the renderer (such as React DOM)

**Comment by lblblong** [comment]
支持在 vue3 中使用的，我添加了一个 vue3 中使用的示例，你可以参考下
https://github.com/lblblong/tarojs-router-next/tree/master/examples/vue3

**Comment by qianyihao123** [comment]
我能加您个微信吗, 不知道是不是我的使用方式有问题  依旧还是没有起效果

**Comment by lblblong** [comment]
你这个报错可能是因为 react 和 React DOM 版本不匹配，你更新 react-dom 的版本到最新的试试

**Comment by qianyihao123** [comment]
这是父页面, 此时我需要跳转至子页面并传入一个'content'的值
![1](https://user-images.githubusercontent.com/49771966/114113433-289fff00-9911-11eb-96b5-c30f6e413b51.png)
此时子页面获取数据

**Comment by qianyihao123** [comment]
这是父页面 此时跳转至子页面并传入一个'content'的值, 跳转是可以进行跳转的
![1](https://user-images.githubusercontent.com/49771966/114113689-d6aba900-9911-11eb-9c5a-14960d0b48f9.png)
然后再在子页面获取数据
![2](https://user-images.githubusercontent.com/49771966/114113713-e5925b80-9911-11eb-9613-3d337217d7f6.png)
最后打印的结果为undefined
![3](https://user-images.githubusercontent.com/49771966/114113731-f3e07780-9911-11eb-902c-73c50f97b799.png)

**Comment by lblblong** [comment]
> 这是父页面 此时跳转至子页面并传入一个'content'的值, 跳转是可以进行跳转的
> ![1](https://user-images.githubusercontent.com/49771966/114113689-d6aba900-9911-11eb-9c5a-14960d0b48f9.png)
> 然后再在子页面获取数据
> ![2](https://user-images.githubusercontent.com/49771966/114113713-e5925b80-9911-11eb-9613-3d337217d7f6.png)
> 最后打印的结果为undefined
> ![3](https://user-images.githubusercontent.com/49771966/114113731-f3e07780-9911-11eb-902c-73c50f97b799.png)

你传过去的是 params，Router.getData 是获取不到的，参考以下获取方法
```typescript
import { getCurrentInstance } from '@tarojs/taro'

onLoad () {
    const params = getCurrentInstance().router?.params,
}
```
如果在onLoad生命周期像这样也拿不到参数，可以换到 onShow 生命周期去拿参数试试看

**Comment by qianyihao123** [comment]
谢啦大兄弟, 通过你这种方式可以获取到, 而且你最新更新的useRouterVue不错

**Comment by lblblong** [comment]
嗯，通过 useRouterVue 拿参数会更好些
